label: Meta
preset: page
pages: false
icon: globe

fields:
  titletag:
    label: Title Tag
    type: text
    help: Your website’s name. While it should be a bit descriptive, try to limit it at 50 characters.
  description:
    label: Meta Description
    type: textarea
    size: small
    buttons: false
    help: A short summary to get people an idea of what to expect when visiting your website. Try to limit it at 100 characters.
  website:
    label: Website Url
    type: url
    help: The address people will type in to get to your website.
sidebar:
  metaimage:
    headline: Meta Image
    type: files
    layout: cards
    image:
      cover: true
      ratio: 16/9
    max: 1
    size: small
    info: '{{ file.dimensions }}'
