title: User

fields:
  website:
    label: Website
    type: url
    width: 1/3
  email:
    label: Email
    type: email
    before: contact us at
    width: 1/3
  instagram:
    label: Instagram
    type: url
    icon: instagram
    width: 1/3
